rosarm:
# Publish all joint states -----------------------------------
 joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

 arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
     - joint_1
     - shoulder
     - elbow
     - wrist

 gains:
    shoulder: {p: 100,  d: 1, i: 1, i_clamp: 1}
    joint_1: {p: 100,  d: 1, i: 1, i_clamp: 1}
    elbow: {p: 100,  d: 1, i: 1, i_clamp: 1}
    wrist: {p: 100,  d: 1, i: 1, i_clamp: 1}
